services:
    Brainbits\Blocking\Owner\OwnerFactoryInterface:
        class: Brainbits\Blocking\Owner\SymfonySessionOwnerFactory
        arguments:
            - '@Symfony\Component\HttpFoundation\RequestStack'
