
brainbits_blocking_block:
    path: /blocking/block/{identifier}
    controller: Brainbits\Blocking\Bundle\Controller\BlockingController::blockAction

brainbits_blocking_unblock:
    path: /blocking/unblock/{identifier}
    controller: Brainbits\Blocking\Bundle\Controller\BlockingController::unblockAction
