services:
    Brainbits\Blocking\Blocker:
        arguments:
            - '@Brainbits\Blocking\Storage\StorageInterface'
            - '@Brainbits\Blocking\Owner\OwnerFactoryInterface'


    Brainbits\Blocking\Bundle\Controller\BlockingController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Brainbits\Blocking\Blocker'

